#!/usr/bin/python3
# EASY-INSTALL-DEV-SCRIPT: 'eufs-rqt==2.0.0','eufs_robot_steering_gui'
__requires__ = 'eufs-rqt==2.0.0'
__import__('pkg_resources').require('eufs-rqt==2.0.0')
__file__ = '/home/gustavo/eufs_sim_teste/build/eufs_rqt/scripts/eufs_robot_steering_gui'
with open(__file__) as f:
    exec(compile(f.read(), __file__, 'exec'))
